#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
source_file="$1"
destination="$3@$2:~/"
PATH_TO_SSH_KEY="$4"
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$source_file" "$destination"
scp="$?"
if [ $scp -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer failed."
fi
